### ISSUE TITLE
SetImmediate is not defined.

### ISSUE THREAD

**Issue by eddiecarbin** [djipco/chrome-apps-serialport#2]
Hello, I am using NW React Typescript and getting the following error.

Error handling response: ReferenceError: setImmediate is not defined 

Doing some research I believe it's a node-only feature?

The setImmediate() method is not supported by most browsers. Therefore, it throws a ReferenceError: setImmediate is not defined .

**Comment by eddiecarbin** [comment]
As a quick fixed to the issueI put this in my index html 
<script>
  window.setImmediate = window.setTimeout;
</script>

**Comment by djipco** [comment]
Thanks for reporting. Release 1.0.9 should fix this problem. Can you test it and report back? It's available now on NPM.

**Comment by eddiecarbin** [comment]
Thank you!  looks good!
